AWSTemplateFormatVersion: '2010-09-09'
Description: pihole (using Quad9 DNS)/pivpn (Wireguard setup) ready to use stack

Parameters:
  VPCID:
    Type: AWS::EC2::VPC::Id
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  AMIID:
    Type: String
    Default: ami-0c1c30571d2dae5c9
  KMSID:
    Type: String
  WGPort:
    Type: Number
    Default: 51820

Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - Label: 
          default: "Network Configuration"
        Parameters: 
          - VPCID
          - SubnetId
      - Label: 
          default: "EC2 Configuration"
        Parameters:
          - AMIID 
          - KMSID
      - Label: 
          default: "PiVPN Configuration"
        Parameters:
          - WGPort
    ParameterLabels:
      VPCID:
        default: VPC
      SubnetId:
        default: Subnet
      AMIID:
        default: AMI id for the image you want to use (e.g. Ubuntu ami-0c1c30571d2dae5c9). 
      KMSID:
        default: "KMS id used to encrypt filesystem (KMS > AWS managed keys, default aws/ebs Key ID is fine)"
      WGPort:
        default: "Choose Wireguard listen port"

Resources:
  WireguardElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Tags: 
        - Key: Name
          Value: pivpn-pihole
  WireguardSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: pivpn-pihole-sg
      GroupDescription: Security group for WireguardNetworkInterface
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      SecurityGroupIngress:
        - IpProtocol: udp
          FromPort: !Sub "${WGPort}"
          ToPort: !Sub "${WGPort}"
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: pivpn-pihole
      VpcId: !Sub "${VPCID}"
  WireguardNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      SourceDestCheck: False
      GroupSet:
        - !Ref WireguardSecurityGroup
      SubnetId: !Sub "${SubnetId}"
      Tags:
      - Key: Name
        Value: pivpn-pihole
  WireguardElasticIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      AllocationId: !GetAtt WireguardElasticIP.AllocationId
      NetworkInterfaceId: !Ref WireguardNetworkInterface
  EC2SSMRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      RoleName: pivpn-pihole-ec2-ssm-role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      Tags:
      - Key: Name
        Value: pivpn-pihole
  EC2SSMProfile:
  Type: "AWS::IAM::InstanceProfile"
  Properties: 
    Path: /
    Roles: 
      - !Ref EC2SSMRole
  WireguardInstance:
    Type: AWS::EC2::Instance
    DependsOn: WireguardElasticIPAssociation
    Properties: 
      ImageId: !Sub "${AMIID}"
      InstanceType: t2.micro
      NetworkInterfaces:
        - NetworkInterfaceId: !Ref WireguardNetworkInterface
          DeviceIndex: 0
      HibernationOptions:
        Configured: True
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs: 
            Encrypted: True
            DeleteOnTermination: True
            KmsKeyId: !Sub "${KMSID}"
            VolumeType: gp2
            VolumeSize: 8
      IamInstanceProfile: !Ref EC2SSMProfile
      Tags:
      - Key: Name
        Value: pivpn-pihole
