AWSTemplateFormatVersion: '2010-09-09'
Description: pihole (using Quad9 DNS)/pivpn (Wireguard setup) ready to use stack

Parameters:

Metadata: 

Resources:
  WireguardElasticIP:
    Type: AWS::EC2::EIP
    Properties:
      Tags: 
        - Key: Name
          Value: pivpn-pihole
